### ISSUE TITLE
Research on finding the data source

### ISSUE THREAD

**Issue by PGGokhale** [Rebel-Scum-Analytical/TeamProject3#7]
Find the data source and procedure about how to load the data in the database which can be used for Machine Learning and providing recommendations/predictions decided in the project proposal.

**Comment by rando010** [comment]
I found a data set on Kaggle that we can append to our database. I removed duplicates from our existing dataset and aligned the columns to match. this dataset had text values for the measurement that I had to remove. 
[kaggle-nutrition-cleaned.zip](https://github.com/Rebel-Scum-Analytical/TeamProject3/files/4497036/kaggle-nutrition-cleaned.zip)
